/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs and is kept here so the
// manually scaffolded project type-checks once dependencies are installed.
